import type { PlayerValue, Position } from "@/lib/types";
import { nextSnakePick } from "@/services/availability";
import { recommendation } from "@/services/draftiq";

export type SessionStatus="SETUP"|"ACTIVE"|"PAUSED"|"COMPLETE";
export interface SessionPick {id:string;pick:number;round:number;slot:number;teamId:string;playerId:string;position:Position;isKeeper:boolean;source:"MANUAL"|"SLEEPER";externalId?:string;selectedAt:Date}
export interface DraftSessionState {id:string;teams:number;rounds:number;userSlot:number;type:"SNAKE"|"LINEAR";status:SessionStatus;currentPick:number;picks:SessionPick[];available:PlayerValue[];updatedAt:Date}
export const teamSlotForPick=(pick:number,teams:number,type:"SNAKE"|"LINEAR")=>{const round=Math.floor((pick-1)/teams)+1,index=(pick-1)%teams+1;return type==="SNAKE"&&round%2===0?teams-index+1:index};
export function startSession(input:Omit<DraftSessionState,"status"|"currentPick"|"picks"|"updatedAt">):DraftSessionState{return {...input,status:"ACTIVE",currentPick:1,picks:[],updatedAt:new Date()}}
export function selectPlayer(state:DraftSessionState,playerId:string,teamId?:string,source:"MANUAL"|"SLEEPER"="MANUAL",externalId?:string,isKeeper=false):DraftSessionState{if(state.status!=="ACTIVE")throw new Error("Draft session is not active");if(state.picks.some(p=>p.playerId===playerId)||!state.available.some(p=>p.id===playerId))throw new Error("Player is unavailable");if(externalId&&state.picks.some(p=>p.externalId===externalId))return state;const player=state.available.find(p=>p.id===playerId)!;const pick=state.currentPick,slot=teamSlotForPick(pick,state.teams,state.type);const selection:SessionPick={id:externalId??`${state.id}:${pick}`,pick,round:Math.floor((pick-1)/state.teams)+1,slot,teamId:teamId??String(slot),playerId,position:player.position,isKeeper,source,externalId,selectedAt:new Date()};return {...state,picks:[...state.picks,selection],available:state.available.filter(p=>p.id!==playerId),currentPick:pick+1,status:pick>=state.teams*state.rounds?"COMPLETE":state.status,updatedAt:new Date()}}
export function undoPick(state:DraftSessionState,players:PlayerValue[]):DraftSessionState{const last=state.picks.at(-1);if(!last)return state;const player=players.find(p=>p.id===last.playerId);return {...state,picks:state.picks.slice(0,-1),available:player?[...state.available,player]:state.available,currentPick:last.pick,status:"ACTIVE",updatedAt:new Date()}}
export function editPick(state:DraftSessionState,pick:number,playerId:string,players:PlayerValue[]):DraftSessionState{const existing=state.picks.find(p=>p.pick===pick);if(!existing)throw new Error("Pick not found");if(state.picks.some(p=>p.playerId===playerId&&p.pick!==pick))throw new Error("Player is unavailable");const replacement=players.find(p=>p.id===playerId);if(!replacement)throw new Error("Player not found");const old=players.find(p=>p.id===existing.playerId);return {...state,picks:state.picks.map(p=>p.pick===pick?{...p,playerId,position:replacement.position}:p),available:[...state.available.filter(p=>p.id!==playerId),...(old?[old]:[])],updatedAt:new Date()}}
export const setPaused=(state:DraftSessionState,paused:boolean):DraftSessionState=>({...state,status:paused?"PAUSED":"ACTIVE",updatedAt:new Date()});
export function sessionView(state:DraftSessionState){const nextPick=state.type==="SNAKE"?nextSnakePick(state.currentPick-1||1,state.teams,state.userSlot):state.currentPick+(state.teams-state.userSlot+1);const recommendations=state.available.map(p=>({...p,...recommendation(p,nextPick)})).sort((a,b)=>b.draftIq+b.urgency*.08-(a.draftIq+a.urgency*.08));const rosters=state.picks.reduce<Record<string,SessionPick[]>>((all,pick)=>{(all[pick.teamId]??=[]).push(pick);return all},{});return {...state,nextUserPick:nextPick,recommendations,rosters};}
