import { describe,expect,it,vi } from "vitest";
import { normalizeDraft,normalizePicks,normalizeScoring,normalizeTeams,SleeperProviderError } from "@/providers/sleeper";
import { stableManagerKey,analyzeOpponent } from "@/services/opponent";
import { editPick,selectPlayer,setPaused,startSession,teamSlotForPick,undoPick,sessionView } from "@/services/draft-session";
import { applyRemotePicks } from "@/services/live-sync";
import { demoPlayers } from "@/lib/demo";
import { normalizeSportsGameOdds,sportsGameOddsProvider } from "@/providers/odds/sports-game-odds";

describe("Sleeper normalization",()=>{it("normalizes custom scoring without assuming PPR",()=>{const scoring=normalizeScoring({rec:.5,pass_td:6,bonus_rec_te:.5});expect(scoring.reception).toBe(.5);expect(scoring.passingTouchdown).toBe(6);expect(scoring.tePremium).toBe(.5)});it("normalizes managers, teams, picks, keepers and snake slots",()=>{const teams=normalizeTeams([{roster_id:2,owner_id:"u1",players:["p1"],settings:{wins:9}}],[{user_id:"u1",username:"sharp"}]);expect(teams[0]).toMatchObject({externalId:"2",managerExternalId:"u1",rosterPlayerIds:["p1"]});const rawPicks=[{pick_no:1,round:1,draft_slot:1,player_id:"p1",roster_id:2,is_keeper:true}];expect(normalizePicks(rawPicks)[0].isKeeper).toBe(true);expect(normalizeDraft({draft_id:"d",status:"drafting",type:"snake",settings:{rounds:16,teams:12},slot_to_roster_id:{"1":2}},rawPicks).slotToTeam[1]).toBe("2")});it("provides a typed provider error",()=>expect(new SleeperProviderError(429,"limited").status).toBe(429))});

describe("manager intelligence",()=>{it("keeps identity stable across team names and seasons",()=>expect(stableManagerKey("SLEEPER","user-123")).toBe("sleeper:user-123"));it("excludes keepers and shrinks small samples",()=>{const picks=[{managerId:"m",season:2025,round:1,position:"QB" as const,pick:2,isKeeper:true},{managerId:"m",season:2025,round:2,position:"RB" as const,pick:14,adp:18},{managerId:"other",season:2025,round:2,position:"WR" as const,pick:15}];const result=analyzeOpponent("m",picks);expect(result.sampleSize).toBe(1);expect(result.confidence).toBeLessThan(10);expect(result.qbAverageRound).toBeNull();expect(result.averageReach).toBeLessThan(0)})});

describe("persistent draft domain",()=>{const fresh=()=>startSession({id:"s",teams:4,rounds:3,userSlot:2,type:"SNAKE",available:demoPlayers});it("calculates snake order",()=>{expect([1,2,3,4,4,3,2,1].map((_,i)=>teamSlotForPick(i+1,4,"SNAKE"))).toEqual([1,2,3,4,4,3,2,1])});it("selects, removes, reranks and undoes",()=>{const selected=selectPlayer(fresh(),"p1");expect(selected.available.some(p=>p.id==="p1")).toBe(false);expect(selected.picks[0].teamId).toBe("1");expect(sessionView(selected).recommendations.some(p=>p.id==="p1")).toBe(false);const undone=undoPick(selected,demoPlayers);expect(undone.available.some(p=>p.id==="p1")).toBe(true);expect(undone.currentPick).toBe(1)});it("edits and pauses picks",()=>{let state=selectPlayer(fresh(),"p1");state=editPick(state,1,"p2",demoPlayers);expect(state.picks[0].playerId).toBe("p2");expect(state.available.some(p=>p.id==="p1")).toBe(true);expect(setPaused(state,true).status).toBe("PAUSED")});it("rejects an unavailable player",()=>{const selected=selectPlayer(fresh(),"p1");expect(()=>selectPlayer(selected,"p1")).toThrow("unavailable")})});

describe("live sync",()=>{it("is idempotent and maps external player ids",()=>{const state=startSession({id:"s",teams:4,rounds:3,userSlot:2,type:"SNAKE",available:demoPlayers}),remote=[{externalId:"remote-1",pick:1,round:1,slot:1,playerExternalId:"sleeper-p1",teamExternalId:"1",isKeeper:false}],first=applyRemotePicks(state,remote,{"sleeper-p1":"p1"}),second=applyRemotePicks(first.state,remote,{"sleeper-p1":"p1"});expect(first.inserted).toBe(1);expect(second.inserted).toBe(0);expect(second.state.picks).toHaveLength(1)});it("reports unresolved identities without silently matching",()=>{const state=startSession({id:"s",teams:4,rounds:3,userSlot:2,type:"SNAKE",available:demoPlayers}),result=applyRemotePicks(state,[{externalId:"x",pick:1,round:1,slot:1,playerExternalId:"unknown",isKeeper:false}],{});expect(result.unresolved).toEqual(["unknown"]);expect(result.inserted).toBe(0)})});

describe("SportsGameOdds",()=>{it("stores paired prices and never relabels weekly props",()=>{const outcomes=[{playerID:"op1",marketName:"player_receptions",periodID:"season",line:80.5,sportsbook:"Book",sideID:"over",bookOdds:-120,updatedAt:"2026-08-20T00:00:00Z"},{playerID:"op1",marketName:"player_receptions",periodID:"season",line:80.5,sportsbook:"Book",sideID:"under",bookOdds:100,updatedAt:"2026-08-20T00:00:00Z"},{playerID:"op1",marketName:"player_receptions",periodID:"week_1",line:5.5,sportsbook:"Book",sideID:"over",bookOdds:-110,updatedAt:"2026-08-20T00:00:00Z"},{playerID:"op1",marketName:"player_receptions",periodID:"week_1",line:5.5,sportsbook:"Book",sideID:"under",bookOdds:-110,updatedAt:"2026-08-20T00:00:00Z"}],result=normalizeSportsGameOdds([{odds:outcomes}]);expect(result.lines.map(l=>l.marketType)).toEqual(["SEASON","WEEKLY"]);expect(result.lines[0]).toMatchObject({overPrice:-120,underPrice:100,line:80.5})});it("reports unclassified markets as unavailable",()=>{const result=normalizeSportsGameOdds([{odds:[{playerID:"p",marketName:"mystery",sportsbook:"Book",line:1,sideID:"over",bookOdds:-110}]}]);expect(result.lines).toHaveLength(0);expect(result.coverage[0]).toMatchObject({available:false,marketType:"UNAVAILABLE"})});it("fails explicitly without credentials",async()=>{vi.stubEnv("SPORTS_GAME_ODDS_API_KEY","");await expect(sportsGameOddsProvider.lines({season:2026,scoring:"PPR"})).rejects.toThrow("not configured");vi.unstubAllEnvs()})});
