"use client";
import {useState} from "react";
import type {NormalizedKeeper,NormalizedLeagueProfile,NormalizedManager} from "@/providers";

const steps=["Connect","Choose League","Verify League","Keepers","Draft Ready"];
const scoringSummary=(league:NormalizedLeagueProfile)=>league.scoring.reception===1?"PPR":league.scoring.reception===.5?"Half PPR":league.scoring.reception===0?"Standard":"Custom";

export function AddLeague(){
  const [step,setStep]=useState(0),[username,setUsername]=useState(""),[manager,setManager]=useState<NormalizedManager>(),[leagues,setLeagues]=useState<NormalizedLeagueProfile[]>([]),[selected,setSelected]=useState<NormalizedLeagueProfile>(),[history,setHistory]=useState<NormalizedLeagueProfile[]>([]),[keepers,setKeepers]=useState<NormalizedKeeper[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const userTeam=selected?.teams.find(team=>team.managerExternalId===manager?.externalId),userKeepers=keepers.filter(keeper=>keeper.teamExternalId===userTeam?.externalId);
  async function connect(){setBusy(true);setMessage("");const response=await fetch("/api/sleeper/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,season:new Date().getFullYear()})}),payload=await response.json();setBusy(false);if(!response.ok){setMessage(payload.error);return}setManager(payload.data.manager);setLeagues(payload.data.leagues);setStep(1);setMessage(payload.data.leagues.length?"Choose a league below.":"No Sleeper leagues were found for the current season.")}
  async function choose(league:NormalizedLeagueProfile){setBusy(true);setMessage("Loading managers, rosters, draft, keepers, and history…");const response=await fetch(`/api/sleeper/leagues/${league.externalId}?userId=${encodeURIComponent(manager?.externalId??"")}`),payload=await response.json();setBusy(false);if(!response.ok){setMessage(payload.error);return}setSelected(payload.data.profile);setHistory(payload.data.history);setKeepers(payload.data.profile.keepers);setStep(2);setMessage("")}
  function updateKeeper(index:number,patch:Partial<NormalizedKeeper>){setKeepers(current=>current.map((keeper,i)=>i===index?{...keeper,...patch}:keeper))}
  async function finalize(){if(!selected)return;setBusy(true);setMessage("Saving current league…");const current={...selected,keepers};const response=await fetch("/api/leagues",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile:current})}),payload=await response.json();if(!response.ok){setBusy(false);setMessage(payload.error);return}const historicalFailures:string[]=[];for(const old of history){const result=await fetch("/api/leagues",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile:old})});if(!result.ok)historicalFailures.push(old.name)}const activeResponse=await fetch("/api/active-league",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leagueId:payload.data.id})});if(!activeResponse.ok){const activePayload=await activeResponse.json();setBusy(false);setMessage(activePayload.error??"League saved, but could not be made active.");return}setBusy(false);setStep(4);setMessage(historicalFailures.length?`Current league is active. Historical import skipped ${historicalFailures.length} season(s).`:`${selected.name} is saved and active.`)}
  return <section className="panel onboarding"><div className="steps">{steps.map((name,i)=><span key={name} className={i<=step?"active":""}>{i+1}<small>{name}</small></span>)}</div>
    {step===0&&<><h2>Connect Sleeper</h2><p>Enter your Sleeper username. No password is required.</p><input value={username} onChange={event=>setUsername(event.target.value)} placeholder="Sleeper username"/><button className="primary" disabled={busy||!username.trim()} onClick={connect}>{busy?"Connecting…":"Find my leagues"}</button></>}
    {step===1&&<><h2>Choose a league</h2><div className="league-options">{leagues.map(league=><button className="provider" key={league.externalId} disabled={busy} onClick={()=>choose(league)}><b>{league.name}</b><small>{league.season} · {league.size} teams · {scoringSummary(league)} · {league.currentDraft?.status??"No draft"}</small></button>)}</div></>}
    {step===2&&selected&&<><h2>Verify League</h2><div className="verify-grid"><p><small>League</small><b>{selected.name}</b></p><p><small>Season / teams</small>{selected.season} · {selected.size}</p><p><small>Scoring</small>{scoringSummary(selected)} · Pass TD {selected.scoring.passingTouchdown}</p><p><small>Draft</small>{selected.draftType} · {selected.currentDraft?.status??"Unavailable"}</p><p><small>Your team</small>{userTeam?.name??"No roster assigned"}</p><p><small>Your draft slot</small>{selected.userDraftSlot??"Unavailable"}</p><p><small>Previous league</small>{selected.previousLeagueId??"None"}</p><p><small>History found</small>{history.length} previous season(s)</p></div><p><b>Roster:</b> {selected.rosterPositions.join(" · ")}</p><h2>Managers and teams</h2><table><thead><tr><th>Manager</th><th>Team</th><th>Players</th><th>You</th></tr></thead><tbody>{selected.managers.map(member=>{const team=selected.teams.find(value=>value.managerExternalId===member.externalId);return <tr key={member.externalId}><td>{member.displayName}</td><td>{team?.name??"Unassigned"}</td><td>{team?.rosterPlayerIds.length??0}</td><td>{member.externalId===manager?.externalId?"Yes":""}</td></tr>})}</tbody></table><button className="primary" onClick={()=>setStep(3)}>Settings verified</button></>}
    {step===3&&selected&&<><h2>Keeper verification</h2><p>{keepers.length?`${keepers.length} keeper pick(s) detected. Correct rounds or remove incorrect entries before saving.`:"Sleeper did not provide keeper metadata. You can continue and add keepers manually."}</p>{keepers.map((keeper,index)=><div className="keeper-row" key={keeper.sourcePickId??`${keeper.playerExternalId}:${index}`}><label><small>Player</small><input aria-label="Keeper player" title={keeper.playerName} value={keeper.playerExternalId} onChange={event=>updateKeeper(index,{playerExternalId:event.target.value})}/>{keeper.playerName&&<small>{keeper.playerName}</small>}</label><label><small>Team</small><input aria-label="Keeper team" value={keeper.teamExternalId} onChange={event=>updateKeeper(index,{teamExternalId:event.target.value})}/></label><label><small>Round</small><input aria-label="Keeper round" type="number" value={keeper.round??""} onChange={event=>updateKeeper(index,{round:event.target.value?Number(event.target.value):undefined})}/></label><button className="pill" onClick={()=>setKeepers(current=>current.filter((_,i)=>i!==index))}>Remove</button></div>)}<button className="pill" onClick={()=>setKeepers(current=>[...current,{playerExternalId:"",teamExternalId:userTeam?.externalId??"",round:undefined}])}>Add keeper manually</button><p>Your team has {userKeepers.length} detected keeper(s).</p><button className="primary" disabled={busy} onClick={finalize}>{busy?"Importing…":"Save and Set Active"}</button></>}
    {step===4&&<><h2>Draft Ready</h2><p className="positive">{message}</p><a className="primary" href="/draft-room">Open DraftIQ</a></>}
    {message&&step!==4&&<p className={message.includes("unavailable")||message.includes("could not")?"danger":"warning"}>{message}</p>}
  </section>
}
