import {getDb} from "@/lib/db";
import {demoPlayers} from "@/lib/demo";
import {isDemoMode} from "@/lib/runtime";
import type {PlayerValue,ScoringRules} from "@/lib/types";
import {PPR_SCORING} from "@/lib/types";
import {fantasyPoints} from "@/services/scoring";
import {assignTiers} from "@/services/tiers";
import {getActiveLeague} from "@/server/active-league";

export interface UniverseOptions {draftId?:string;scoring?:ScoringRules;demoMode?:boolean;realLoader?:()=>Promise<PlayerValue[]>}
const stale=(date:Date|null|undefined,hours=36)=>Boolean(date&&Date.now()-date.getTime()>hours*36e5);
const formatFor=(rules:ScoringRules)=>rules.reception===1?"PPR":rules.reception===.5?"HALF_PPR":rules.reception===0?"STANDARD":"CUSTOM";
export const resolveScoringRules=(explicit:ScoringRules|undefined,draft:ScoringRules|undefined,active:ScoringRules|undefined)=>explicit??draft??active??PPR_SCORING;
export function calculateNextPick(input:{currentPick:number;teams:number;userSlot:number;draftType:"SNAKE"|"LINEAR"}){return Array.from({length:input.teams*2},(_,index)=>input.currentPick+index).find(pick=>{const round=Math.floor((pick-1)/input.teams)+1,within=(pick-1)%input.teams+1,slot=input.draftType==="SNAKE"&&round%2===0?input.teams-within+1:within;return slot===input.userSlot})??input.currentPick}

export async function getPlayerUniverse(options:UniverseOptions={}):Promise<PlayerValue[]>{
  const demo=options.demoMode??isDemoMode();if(demo)return demoPlayers;if(options.realLoader)return options.realLoader();
  const db=getDb() as any,active=options.draftId?null:await getActiveLeague(),draftId=options.draftId??active?.drafts?.[0]?.id,draft=draftId?await db.draft.findUnique({where:{id:draftId},include:{league:{include:{settings:true}}}}):null,settings=draft?.league.settings??active?.settings,rules=resolveScoringRules(options.scoring,draft?.league.settings?.scoring,active?.settings?.scoring),leagueSize=settings?.teams,scoringFormat=formatFor(rules);
  const players=await db.player.findMany({where:{active:true,picks:draftId?{none:{draftId}}:undefined},include:{adp:{include:{provider:true},orderBy:{capturedAt:"desc"},take:12},projections:{include:{snapshot:{include:{provider:true}}},orderBy:{snapshot:{capturedAt:"desc"}},take:1},vegasProjections:{orderBy:{capturedAt:"desc"},take:1},vegasScores:{orderBy:{capturedAt:"desc"},take:1},confidenceScores:{orderBy:{capturedAt:"desc"},take:1},draftIqScores:{orderBy:{capturedAt:"desc"},take:1},tiers:{orderBy:{capturedAt:"desc"},take:1}}});
  const values:PlayerValue[]=players.map((player:any)=>{const adp=player.adp.find((item:any)=>(!leagueSize||!item.leagueSize||item.leagueSize===leagueSize)&&[scoringFormat,"PPR"].includes(item.scoring))??player.adp[0],projection=player.projections[0],vegas=player.vegasProjections[0],stored=player.draftIqScores[0],projected=projection?.stats?fantasyPoints(projection.stats,rules,player.position):projection?.fantasyPoints??0,vegasPoints=vegas?.stats?fantasyPoints(vegas.stats,rules,player.position):vegas?.fantasyPoints??projected,coverage=player.confidenceScores[0]?.score??0,signalCount=Number(Boolean(adp))+Number(Boolean(projection))+Number(Boolean(vegas)),confidence=Math.round((coverage*.6)+(signalCount/3)*40);return {id:player.id,name:player.name,position:player.position,team:player.team,marketAdp:adp?.mean??999,adpSd:adp?.deviation||15,vegasAdp:stored?.vegasAdp??999,vegasPoints,fantasyPoints:projected,vegasScore:player.vegasScores[0]?.score??50,confidence,vorp:stored?.vorpScore??0,tier:player.tiers[0]?.tier??99,draftIq:stored?.overall??Math.max(0,Math.min(100,45+signalCount*5+(vegasPoints-projected)*.15)),provenance:{adp:{source:adp?.provider?.name??"FantasyFootballCalculator",updatedAt:adp?.capturedAt??null,status:adp?(stale(adp.capturedAt)?"STALE":"AVAILABLE"):"NO_COVERAGE"},projection:{source:projection?.snapshot?.provider?.name??"FantasyPros",updatedAt:projection?.snapshot?.capturedAt??null,status:projection?(stale(projection.snapshot.capturedAt)?"STALE":"AVAILABLE"):process.env.FANTASYPROS_API_KEY?"NO_COVERAGE":"NOT_CONFIGURED"},vegas:{source:"SportsGameOdds",updatedAt:vegas?.capturedAt??null,status:vegas?(stale(vegas.capturedAt,6)?"STALE":"AVAILABLE"):process.env.SPORTS_GAME_ODDS_API_KEY?"NO_COVERAGE":"NOT_CONFIGURED"}}}});
  for(const position of ["QB","RB","WR","TE"] as const){const peers=values.filter(value=>value.position===position).sort((a,b)=>b.vegasPoints-a.vegasPoints),starterCount=Math.max(1,(leagueSize??12)*(position==="QB"||position==="TE"?1:2)),replacement=peers[Math.min(peers.length-1,starterCount)]?.vegasPoints??0,tiers=assignTiers(peers.map(value=>value.vegasPoints),8);peers.forEach((value,index)=>{if(!value.vorp)value.vorp=Math.max(0,value.vegasPoints-replacement);if(value.tier===99)value.tier=tiers[index]})}
  return values.sort((a,b)=>b.draftIq-a.draftIq);
}

export async function getDraftContext(draftId?:string){const db=getDb() as any,active=await getActiveLeague(),id=draftId??active?.drafts?.[0]?.id;if(!id||!active&&!draftId)return null;const draft=await db.draft.findUnique({where:{id},include:{league:{include:{settings:true}}}});if(!draft)return null;const teams=draft.league.settings.teams,userSlot=draft.userSlot??draft.league.settings.draftSlot,currentPick=draft.currentPick,nextUserPick=calculateNextPick({currentPick,teams,userSlot,draftType:draft.league.settings.draftType});return {leagueId:draft.leagueId,leagueName:draft.league.name,currentPick,round:Math.floor((currentPick-1)/teams)+1,teams,userSlot,nextUserPick,picksUntilUser:Math.max(0,nextUserPick-currentPick),draftType:draft.league.settings.draftType,scoring:draft.league.settings.scoring,roster:draft.league.settings.roster,draftId:id,externalDraftId:draft.externalId,platform:draft.platform,status:draft.status,lastSyncedAt:draft.lastSyncedAt}}
