import type { ADPProvider, NormalizedADP, ProviderContext } from "@/providers";
import type { Position } from "@/lib/types";

type FfcPlayer={player_id?:string;name:string;position:string;team?:string;adp:number;stdev?:number;times_drafted?:number};
type FfcPayload={players?:FfcPlayer[]};
const formats:Record<string,string>={STANDARD:"standard",HALF_PPR:"half-ppr",PPR:"ppr",TWO_QB:"2qb","2QB":"2qb"};
export function normalizeFantasyFootballCalculator(payload:FfcPayload,input:{format:string;leagueSize:number;season:number;capturedAt?:Date}):NormalizedADP[]{return (payload.players??[]).filter(p=>["QB","RB","WR","TE","K","DST"].includes(p.position.toUpperCase())).map(p=>({sourceId:p.player_id,name:p.name,team:p.team,position:p.position.toUpperCase() as Position,mean:Number(p.adp),deviation:Number(p.stdev??0),format:input.format,leagueSize:input.leagueSize,season:input.season,capturedAt:input.capturedAt??new Date()}))}
export class FantasyFootballCalculatorProvider implements ADPProvider {name="FantasyFootballCalculator";constructor(private readonly format="PPR",private readonly leagueSize=12){}async adp(ctx:ProviderContext){const format=formats[this.format.toUpperCase()]??formats.PPR;if(![8,10,12,14].includes(this.leagueSize))throw new Error("FantasyFootballCalculator supports 8, 10, 12, or 14 teams");const base=process.env.FFC_API_URL??"https://fantasyfootballcalculator.com/api/v1/adp";const url=new URL(`${base}/${format}`);url.searchParams.set("teams",String(this.leagueSize));url.searchParams.set("year",String(ctx.season));const response=await fetch(url,{headers:{Accept:"application/json"},signal:ctx.signal,next:{revalidate:86400}});if(!response.ok)throw new Error(`FantasyFootballCalculator request failed (${response.status})`);return normalizeFantasyFootballCalculator(await response.json() as FfcPayload,{format:this.format,leagueSize:this.leagueSize,season:ctx.season}).map(p=>({sourceId:p.sourceId??`${p.name}:${p.position}`,mean:p.mean,sd:p.deviation}))}}
export async function fetchFantasyFootballCalculator(input:{format:string;leagueSize:number;season:number;signal?:AbortSignal}){const format=formats[input.format.toUpperCase()]??formats.PPR,base=process.env.FFC_API_URL??"https://fantasyfootballcalculator.com/api/v1/adp",url=new URL(`${base}/${format}`);url.searchParams.set("teams",String(input.leagueSize));url.searchParams.set("year",String(input.season));const response=await fetch(url,{headers:{Accept:"application/json"},signal:input.signal,next:{revalidate:86400}});if(!response.ok)throw new Error(`FantasyFootballCalculator request failed (${response.status})`);return normalizeFantasyFootballCalculator(await response.json() as FfcPayload,input)}
