import type { OddsLine, OddsMarketAvailability, OddsProvider, ProviderContext } from "@/providers";

const statAliases:Record<string,OddsLine["stat"]>={passing_yards:"passingYards",passing_touchdowns:"passingTouchdowns",interceptions:"interceptions",rushing_attempts:"rushingAttempts",rushing_yards:"rushingYards",rushing_touchdowns:"rushingTouchdowns",receptions:"receptions",receiving_yards:"receivingYards",receiving_touchdowns:"receivingTouchdowns"};
export interface SportsGameOddsOutcome {id?:string;oddID?:string;playerID?:string;statEntityID?:string;marketName?:string;market?:string;periodID?:string;period?:string;sideID?:string;side?:string;line?:number;sportsbook?:string;book?:string;bookOdds?:string|number;price?:string|number;updatedAt?:string;timestamp?:string}
type ApiEvent={odds?:SportsGameOddsOutcome[]|Record<string,SportsGameOddsOutcome>};

function key(value:string|undefined){return (value??"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")}
function marketType(outcome:SportsGameOddsOutcome):OddsLine["marketType"]|"UNAVAILABLE"{const period=key(outcome.periodID??outcome.period),market=key(outcome.marketName??outcome.market);if(period.includes("season")||market.includes("regular_season")||market.includes("season_total"))return "SEASON";if(period.includes("game")||period.includes("week")||market.includes("game_prop"))return "WEEKLY";if(period.includes("future")||market.includes("award")||market.includes("futures"))return "FUTURE";return "UNAVAILABLE"}
function stat(outcome:SportsGameOddsOutcome){const name=key(outcome.marketName??outcome.market);return Object.entries(statAliases).find(([alias])=>name.includes(alias))?.[1]}
function american(value:string|number|undefined){if(typeof value==="number")return value;const parsed=Number(value?.replace("+",""));return Number.isFinite(parsed)?parsed:undefined}
function flatten(events:ApiEvent[]){return events.flatMap(event=>Array.isArray(event.odds)?event.odds:Object.values(event.odds??{}))}

export function normalizeSportsGameOdds(events:ApiEvent[]):{lines:OddsLine[];coverage:OddsMarketAvailability[]}{const outcomes=flatten(events),coverage:OddsMarketAvailability[]=[],groups=new Map<string,SportsGameOddsOutcome[]>();for(const outcome of outcomes){const type=marketType(outcome),mapped=stat(outcome),market=outcome.marketName??outcome.market??"Unknown market",book=outcome.sportsbook??outcome.book;coverage.push({provider:"SportsGameOdds",market,marketType:type,sportsbook:book,available:type!=="UNAVAILABLE"&&Boolean(mapped),reason:type==="UNAVAILABLE"?"Provider payload does not identify this as season, weekly/game, or futures":!mapped?"Unsupported player-stat market":undefined,observedAt:new Date(outcome.updatedAt??outcome.timestamp??Date.now())});if(type==="UNAVAILABLE"||!mapped||!book||outcome.line===undefined)continue;const groupKey=[outcome.playerID??outcome.statEntityID,mapped,type,book,outcome.line].join("|");groups.set(groupKey,[...(groups.get(groupKey)??[]),outcome])}const lines:OddsLine[]=[];for(const outcomes of groups.values()){const over=outcomes.find(o=>key(o.sideID??o.side)==="over"),under=outcomes.find(o=>key(o.sideID??o.side)==="under"),overPrice=american(over?.bookOdds??over?.price),underPrice=american(under?.bookOdds??under?.price),sample=over??under;if(!over||!under||overPrice===undefined||underPrice===undefined||!sample)continue;lines.push({sourceId:sample.playerID??sample.statEntityID??"",providerId:sample.oddID??sample.id,book:sample.sportsbook??sample.book!,stat:stat(sample)!,line:sample.line!,overPrice,underPrice,marketType:marketType(sample) as OddsLine["marketType"],observedAt:new Date(sample.updatedAt??sample.timestamp??Date.now())})}return {lines,coverage}}
async function fetchEvents(ctx:ProviderContext){const apiKey=process.env.SPORTS_GAME_ODDS_API_KEY;if(!apiKey)throw new Error("SPORTS_GAME_ODDS_API_KEY is not configured");const url=new URL(process.env.SPORTS_GAME_ODDS_API_URL??"https://api.sportsgameodds.com/v2/events/");url.searchParams.set("apiKey",apiKey);url.searchParams.set("leagueID","NFL");url.searchParams.set("oddsAvailable","true");const response=await fetch(url,{headers:{Accept:"application/json"},signal:ctx.signal});if(!response.ok)throw new Error(`SportsGameOdds request failed (${response.status})`);const payload=await response.json() as {data?:ApiEvent[]};return payload.data??[]}
export const sportsGameOddsProvider:OddsProvider={name:"SportsGameOdds",async lines(ctx){return normalizeSportsGameOdds(await fetchEvents(ctx)).lines},async coverage(ctx){return normalizeSportsGameOdds(await fetchEvents(ctx)).coverage}};
